# force run: 1
dist: xenial
language: c
compiler:
#  - clang
  - gcc
python:
  - "3.6"
sudo: required
before_install:
    - sudo -H DEBIAN_FRONTEND=noninteractive apt-get update
    - sudo apt-get -y install python3-pip python-dev
    - sudo pip3 install -U setuptools
    - sudo pip3 install -U virtualenvwrapper
    - which python
    - python --version
#    - sudo -H PATH="${PATH}:/usr/local/clang-3.4/bin" pip3 install -r requirements.txt
    - pip3 install --user cpp-coveralls
env:
  global:
    - COVERALLS_PARALLEL=true
script:
    sh -x ./scripts/do-test.sh
#after_success:
#  - for f in `make -f tests/Makefile list_tests`;
#    do
#      cat tests/${f}.log;
#    done
#  - if [ "${CC}" = "gcc" ];
#    then
#      sh -x ./scripts/submit-coverage.sh ;
#    fi
deploy:
  provider: pages
  condition: $CC == "gcc"
  file: doc/user_manual.xml doc/release_info.xml
#  file_glob: true
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  repo: sobomax/rtptestdoc
  target_branch: $TRAVIS_BRANCH
  on:
    branch: master
  on:
    branch: docdeploy

notifications:
  webhooks: https://coveralls.io/webhook
